---
- hosts: all
  gather_facts: False

  tasks:
  - name: Generate Intial Configuration Files
    template:
      src: templates/initial_config.j2
      dest: /configurations/pan-os/initial_configurations/initial_configuration-{{ inventory_hostname }}.txt
    delegate_to: localhost
...