
---
- hosts: all
  gather_facts: False

  tasks:
  - name: Run exec command
    panos_op:
      ip_address: '{{ inventory_hostname }}'
      api_key: '{{ panw_api_token }}'
      cmd: '{{ command }}'
    register: result
  
  - debug:
      var: result.stdout_lines
...